limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;
limit_req_status 429;

upstream app_backend {
    # server nodeapp_blue:4000;
    server nodeapp_blue:4000;
}

server {
    listen 443 ssl;
    server_name webnas.orbitax.com;

    ssl_certificate /etc/letsencrypt/live/webnas.orbitax.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/webnas.orbitax.com/privkey.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header X-XSS-Protection "1; mode=block";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    error_page 429 /429.html;
    location = /429.html {
        internal;
        default_type text/plain;
        return 429 "Too Many Requests - Slow down\n";
    }

    location ~ /\.(env|git|config|htaccess)$ {
        deny all;
    }

    location = /test {
        default_type text/plain;
        return 200 "Test route working\n";
    }

    location /api {
        limit_req zone=api_limit burst=10 nodelay;
        proxy_pass http://app_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /app2 {
        proxy_pass http://nodeapp2:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://app_backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
