apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
spec:
  scaleTargetRef:
    name: worker   # 👉 worker deployment scale হবে

  minReplicaCount: 0
  maxReplicaCount: 5
  pollingInterval: 5
  cooldownPeriod: 30

  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://admin:admin123@rabbitmq.default.svc.cluster.local:5672/%2F
      queueName: jobs
      mode: QueueLength
      value: "1"
