apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp-prod-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - webnas.orbitax.com
    secretName: nodeapp-tls
  rules:
  - host: webnas.orbitax.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodeapp
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodeapp-dev-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - dev.webnas.orbitax.com
    secretName: nodeapp-dev-tls
  rules:
  - host: dev.webnas.orbitax.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nodeapp-dev
            port:
              number: 80
