apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride | default "nodeapp" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride | default "nodeapp" }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride | default "nodeapp" }}
    spec:
      containers:
      - name: nodeapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3000
