apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride | default "nodeapp" }}
  labels:
    app: {{ .Values.nameOverride | default "nodeapp" }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.nameOverride | default "nodeapp" }}
  ports:
    - name: http   # 🔥 VERY IMPORTANT (Prometheus needs this)
      port: 80
      targetPort: 3000
      nodePort: {{ .Values.nodePort }}
