name: Full CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t erfanasir/mysite-nodeapp:${IMAGE_TAG} ./nodeapp

      - name: Push image
        run: |
          docker push erfanasir/mysite-nodeapp:${IMAGE_TAG}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl config get-contexts

      - name: Deploy
        run: |
          export KUBECONFIG=kubeconfig.yaml
          kubectl set image deployment/nodeapp-deployment nodeapp=erfanasir/mysite-nodeapp:${IMAGE_TAG}
          kubectl rollout status deployment/nodeapp-deployment
