name: Full CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          docker build -t erfanasir/mysite-nodeapp:latest ./nodeapp

      - name: Push image
        run: |
          docker push erfanasir/mysite-nodeapp:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml
          kubectl rollout restart deployment/nodeapp-deployment
          kubectl rollout status deployment/nodeapp-deployment
